name: cashito_app
description: "Cashito App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11

  cupertino_icons: ^1.0.8

  # Reactive persistence library
  drift_flutter: ^0.2.4
  drift: ^2.24.0

  fl_chart: ^0.70.2
  flutter_sticky_header: ^0.7.0

  intl: ^0.20.2

  modal_bottom_sheet: ^3.0.0

  path_provider: ^2.1.5
  path: ^1.9.0

  # Sqlite3
  sqlite3_flutter_libs: ^0.5.29+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14

  drift_dev: ^2.24.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/categories/

  fonts:
    - family: Font72
      fonts:
        - asset: assets/fonts/72-Light.ttf
          weight: 200
        - asset: assets/fonts/72-Regular.ttf
          weight: 400
        - asset: assets/fonts/72-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/72-Bold.ttf
          weight: 700
        - asset: assets/fonts/72-Black.ttf
          weight: 800
